user require syntax for partials
edm00se/modernize-ng1 pull request #3
Opened 2018-07-17 01:17 UTC by martell

2018-07-17 02:09 UTC, edm00se commented
Thanks for the PR. I had seen parcel-bundler/parcel#1732 and was waiting for it to be included in a version release to make the changes. Once the npm version bumps and includes the update, I'll be happy to accept and merge this.

2018-07-17 02:10 UTC, edm00se commented on src/js/directives.js
> +      template: require('../partials/nav.html', 'utf8'),
One of the `, 'utf8'` second parameters got missed.

2018-07-17 02:13 UTC, edm00se commented
Thanks for the PR. I had seen parcel-bundler/parcel#1732 and was waiting for it to be incorporated into a version release to do it myself. Once the npm version bumps and includes the update, I'll be happy to accept and merge this.

2018-07-17 02:14 UTC, edm00se requested changes
Thanks for the PR. I had seen parcel-bundler/parcel#1732 and was waiting for it to be included in a version release to make the changes. I am pretty excited for it. Once the npm version bumps and includes the update, I'll be happy to accept and merge this.

2018-07-17 02:14 UTC, edm00se commented on package.json
> +    "parcel-bundler": "parcel-bundler/parcel",
I'd like to wait for the changes to be part of a version release. We'll need to update the version here once that's been done.

2018-07-17 02:14 UTC, edm00se commented on src/js/directives.js
> +      template: require('../partials/nav.html', 'utf8'),
One of the , 'utf8' second parameters got missed.

2018-07-17 18:55 UTC, martell commented
I updated the PR to point to what I expect to be the next release version.

Thanks for working on this project to give people a good example on how to modernize their old angularjs 1.x apps.

2018-08-16 14:58 UTC, edm00se approved these changes

2018-08-17 20:35 UTC, absynce commented
Should this update the [migration guide](https://github.com/edm00se/modernize-ng1/blob/master/docs/Migrate.md#updating-the-router) too? It currently shows an example of the prior way to load partials.

2018-08-17 20:36 UTC, edm00se commented
@absynce Thanks for checking. Once merged I'll make sure to update the migration guide. You're right, it currently shows use of `fs.readFileSync`.

2018-09-30 04:24 UTC, edm00se commented
Thanks again for the PR. It has been incorporated into #6 so it can get released tonight quickly while I had a few minutes. It was an easy way of handling the merge conflict that came up as well as upgrading another dep and adding the package-lock file. The app is now building with parcel 1.10.1! 🎉

I've also updated the `docs/Migrate.md` migration guide to reflect the direct use of `require`. 

For the wayward reader looking for context, the release of `parcel-bundler` after 1.9.7 wound up being `1.10.0`. Blog post: https://medium.com/@devongovett/parcel-v1-10-0-babel-7-flow-elm-and-more-c20736553573

2018-09-30 04:24 UTC, closed without merging

2019-01-15 15:17 UTC, edm00se commented
Support for IE is currently blocked until the html loader handling changes for either:

- the bundle loader not directly depending on `Promise` or `fetch` APIs in the browser (un-polyfilled, before any babel polyfill takes effect)
- the html partials not be separate bundles (appended to the existing bundle)

See #14.